/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCheckinRouteImport } from './routes/app.checkin'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppMoodRouteImport } from './routes/app.mood'
import { Route as AppNudgesRouteImport } from './routes/app.nudges'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppMoodRoute = AppMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => AppRoute,
} as any)
const AppNudgesRoute = AppNudgesRouteImport.update({
  id: '/nudges',
  path: '/nudges',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/community': typeof AppCommunityRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/mood': typeof AppMoodRoute
  '/app/nudges': typeof AppNudgesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/community': typeof AppCommunityRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/mood': typeof AppMoodRoute
  '/app/nudges': typeof AppNudgesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/community': typeof AppCommunityRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/mood': typeof AppMoodRoute
  '/app/nudges': typeof AppNudgesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/app/checkin'
    | '/app/community'
    | '/app/goals'
    | '/app/mood'
    | '/app/nudges'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/app/checkin'
    | '/app/community'
    | '/app/goals'
    | '/app/mood'
    | '/app/nudges'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/app/checkin'
    | '/app/community'
    | '/app/goals'
    | '/app/mood'
    | '/app/nudges'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkin': {
      id: '/app/checkin'
      path: '/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mood': {
      id: '/app/mood'
      path: '/mood'
      fullPath: '/app/mood'
      preLoaderRoute: typeof AppMoodRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nudges': {
      id: '/app/nudges'
      path: '/nudges'
      fullPath: '/app/nudges'
      preLoaderRoute: typeof AppNudgesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCheckinRoute: typeof AppCheckinRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppMoodRoute: typeof AppMoodRoute
  AppNudgesRoute: typeof AppNudgesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckinRoute: AppCheckinRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppMoodRoute: AppMoodRoute,
  AppNudgesRoute: AppNudgesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
